### ISSUE TITLE
add PATH_TO_REPO in ./ocm-container.sh

### ISSUE THREAD

**Issue by georgettica** [drewandersonnz/ocm-container#27]
should we add a param that will allow mounting a REPO into /tmp/repo for local development inside ocm-container

**Comment by iamkirkbater** [comment]
Could be useful.  So far I've been doing the development locally, running a build and then using `docker cp` to push the binary into the container for testing.

**Comment by georgettica** [comment]
Sounds like a good idea aswell, I will see how I feel about it after using it

**Comment by georgettica** [comment]
seems to be fine but there are alot of stuff that we need too pass in for it to work.. if I will have more issues I may speak to you offline on that (in order not to pullute the ISSUES even more)
